#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

echo "Starting mediaman ..."
if [ -f /etc/init/mediaman.conf ]; then
    if pidof /usr/local/bin/mediaman >/dev/null; then
        service mediaman stop || exit $?
    fi
    service mediaman start && echo "Mediaman started."
fi

#DEBHELPER#

exit 0