#!/bin/sh

set -e
set -u

case "$1" in
  remove|remove-in-favour|deconfigure|deconfigure-in-favour)
    if [ -f /etc/init/mediaman.conf ]; then
      echo "Stopping mediaman ..."
      service mediaman stop || exit $?
      echo "mediaman Stopped."
    fi
    ;;

  upgrade|failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0